### ISSUE TITLE
Page Fails To Load Docosaurus

### ISSUE THREAD

**Issue by ben10pedrin** [facebook/react-native-website#3305]
## Description

As a user trying to acces https://reactnative.dev/ when I open the page, it shows a Docosaurus crash log. It would be better if the page could render normally.

Wed, 07 Sep 2022 15:48:15 GMT

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/75655090/188921635-0c405b95-ccef-4cda-a9c2-505dcb29fcda.png">

## Documentation version

Since page is not rendering properly, I can't determine the docs version.

**Comment by ben10pedrin** [comment]
It's now working!

Wed, 07 Sep 2022 20:34:51 GMT

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/75655090/188971986-2a1ec1f1-a627-4eda-9066-dcb06d4c1c10.png">

**Comment by Simek** [comment]
Hello @ben10pedrin 

I was not able to reproduce this nor most of the people I have asked for, but there are few others who reported the problem.

This issue was probably related to the cloud infrastructure issues we use (Netlify) or the cache/CDN problem on the provider side (Cloudflare), and only affects certain parts of the world. 

Happy to see that it has been fixed for you! Let me know, if we can close this issue.

**Comment by ben10pedrin** [comment]
Thanks. Sure, close it!

**Comment by jpmadrigal07** [comment]
I'm running it on my local haha

**Comment by zhigang1992** [comment]
it's still happening on my end, even after switching to different VPNs, and different browsers.

**Comment by KingAmo** [comment]
the same here @Simek 
![image](https://user-images.githubusercontent.com/29938227/189043799-e8b4a265-bc1c-4e6a-8447-66d98fc4d2ed.png)

**Comment by zhigang1992** [comment]
> the same here @Simek 
> 
> ![image](https://user-images.githubusercontent.com/29938227/189043799-e8b4a265-bc1c-4e6a-8447-66d98fc4d2ed.png)
> 
> 

Try force refresh

**Comment by KingAmo** [comment]
@zhigang1992 I have tried everything,  and my colleagues also meet this error

**Comment by zhigang1992** [comment]
https://orange-territory.surge.sh

I've deployed a temporary copy here if anyone still having issue accessing the official one.

**Comment by KingAmo** [comment]
> @zhigang1992 I have tried everything, and my colleagues also meet this error

this works for me, thanks!

**Comment by KingAmo** [comment]
> https://orange-territory.surge.sh
> 
> I've deployed a temporary copy here if anyone still having issues accessing the official one.

this works for me, thanks!

**Comment by slorber** [comment]
if this happens, open the network tab and show what fails to load

It's likely a CSS file that fails to load: paste a screenshot of your network tab, eventually the request details + the URL of the affected file

**Comment by jimji1005** [comment]
not working still, still broken js bundle it seems

https://reactnative.dev/assets/js/main.2d5adc26.js

**Comment by jimji1005** [comment]
as of 9pm pst, no longer seeing this issue
